#pragma once

#include <vector>
#include <memory>

#include "../WaveFunctions/wavefunctioncache.h"

/**
 * @brief Abstract base class for Monte Carlo sampling algorithms.
 * * Defines the interface for generating Markov Chain steps. Derived classes
 * will implement specific algorithms (like standard Metropolis or Metropolis-Hastings).
 * It holds the random number generator and the wave function cache to optimize evaluations.
 */
class MonteCarlo {
public:
    /**
     * @brief Constructs the base Monte Carlo engine.
     * @param rng Unique pointer to the random number generator.
     * @param preferAnalytic Flag to prefer analytical derivatives over numerical ones.
     */
    MonteCarlo(std::unique_ptr<class Random> rng, bool preferAnalytic = true, bool useCache = true);

    // Use the default deconstructor generated by the compiler
    virtual ~MonteCarlo() = default;

    /**
     * @brief Proposes and evaluates a single Monte Carlo step for the system.
     * @param stepParameter The step length or time step (delta t) for the proposal.
     * @param waveFunction Reference to the system's trial wave function.
     * @param particles Vector of unique pointers to the system's particles.
     * @return True if the proposed move was accepted, False if rejected.
     */
    virtual bool step(
        double stepParameter,
        class WaveFunction& waveFunction,
        std::vector<std::unique_ptr<class Particle>>& particles) = 0;

    /**
     * @brief Checks if the solver supports or is configured for analytical calculations.
     * @return True if analytical options are available.
     */
    virtual bool hasAnalyticalOption() = 0;

    /**
     * @brief Retrieves the user preference for analytical derivatives.
     * @return True if analytical derivatives are preferred.
     */
    virtual bool get_preferAnalytic() = 0;

    /**
     * @brief Retrieves the user preference for analytical derivatives.
     * @return True if analytical derivatives are preferred.
     */
    bool get_useCache() { return m_useCache; };

    /**
     * @brief Provides access to the wave function cache.
     * @return Reference to the WaveFunctionCache object.
     */
    WaveFunctionCache& getCache() { return *m_cache; }

protected:
    std::unique_ptr<class Random> m_rng;
    bool m_preferAnalytic;
    bool m_useCache;
    std::unique_ptr<WaveFunctionCache> m_cache;
};
