#pragma once
#include <memory>
#include <vector>
#include <cmath>

/**
 * @brief Abstract base class for all trial wave functions.
 * * This class defines the interface that any specific wave function must implement.
 * It also provides numerical fallback methods for derivatives and quantum forces
 * in case analytical expressions are too complex to derive.
 */
class WaveFunction {
public:
    // Use the default deconstructor generated by the compiler
    virtual ~WaveFunction() = default;

    /**
     * @brief Gets the number of variational parameters.
     * @return Number of parameters.
     */
    int getNumberOfParameters() { return m_numberOfParameters; }

    /**
     * @brief Gets the current values of the variational parameters.
     * @return Constant reference to the parameters vector.
     */
    const std::vector<double>& getParameters() { return m_parameters; }

    /**
     * @brief Defines the lower bounds for the variational parameters during optimization.
     * @return A vector of lower bounds.
     */
    virtual std::vector<double> lowerBounds() const { return {}; }

    /**
     * @brief Defines the upper bounds for the variational parameters during optimization.
     * @return A vector of upper bounds.
     */
    virtual std::vector<double> upperBounds() const { return {}; }

    /**
     * @brief Evaluates the wave function Psi for a given particle configuration.
     * @param particles Vector of system particles.
     * @return The value of Psi.
     */
    virtual double evaluate(std::vector<std::unique_ptr<class Particle>>& particles) = 0;

    /**
     * @brief Evaluates the natural logarithm of the wave function, ln(|Psi|).
     * * Useful to prevent numerical underflow/overflow.
     * @param particles Vector of system particles.
     * @return The value of ln(|Psi|).
     */
    virtual double evaluateLn(std::vector<std::unique_ptr<class Particle>>& particles) {
        return log(evaluate(particles));
    }

    /**
     * @brief Computes the contribution of a single particle to the total ln(|Psi|).
     * * Crucial for optimizing Metropolis steps by caching local changes.
     * @param particles Vector of system particles.
     * @param particle_idx Index of the particle being evaluated.
     * @return The logarithmic contribution of the specified particle.
     */
    virtual double computeParticleLn(std::vector<std::unique_ptr<Particle>>& particles,
        unsigned int particle_idx) { return 0; }

    /**
     * @brief Computes the Laplacian (sum of second derivatives) of the wave function.
     * * Required for evaluating the kinetic energy. Defaults to a numerical method.
     * @param particles Vector of system particles.
     * @return The value of the Laplacian (nabla^2 Psi).
     */
    virtual double computeDoubleDerivative(std::vector<std::unique_ptr<class Particle>>& particles) {
        return computeNumericalDoubleDerivative(particles);
    };

    /**
     * @brief Computes the logarithmic derivative with respect to a variational parameter.
     * * Used by the optimizer to calculate the energy gradient. Defaults to numerical.
     * @param particles Vector of system particles.
     * @param param_idx Index of the parameter to differentiate against.
     * @return The derivative d(ln|Psi|) / d(parameter).
     */
    virtual double computeParamDerivativeLn(std::vector<std::unique_ptr<class Particle>>& particles, unsigned int param_idx) {
        return computeNumericalParamDerivativeLn(particles, param_idx);
    };

    virtual std::vector<double> computeLogParDer_vect(std::vector<std::unique_ptr<class Particle>>& particles);

    /**
     * @brief Computes the quantum drift force acting on a specific particle.
     * * Used in Importance Sampling (Metropolis-Hastings). F = 2 * nabla(Psi) / Psi.
     * @param particles Vector of system particles.
     * @param particle_idx Index of the target particle.
     * @return A vector representing the quantum force in D dimensions.
     */
    virtual std::vector<double> computeQuantumForce(std::vector<std::unique_ptr<class Particle>>& particles, unsigned int particle_idx) {
        return computeNumericalQuantumForce(particles, particle_idx);
    };

    /**
     * @brief Indicates whether the derived class has implemented analytical derivatives.
     * @return True if analytical derivatives are available, False otherwise.
     */
    virtual bool hasAnalyticalDerivative() { return false; }

    // Fallback numerical methods using finite differences
    double computeNumericalDoubleDerivative(std::vector<std::unique_ptr<class Particle>>& particles);
    double computeNumericalParamDerivativeLn(std::vector<std::unique_ptr<class Particle>>& particles, unsigned int param_idx);
    std::vector<double> computeNumericalQuantumForce(std::vector<std::unique_ptr<class Particle>>& particles, unsigned int particle_idx);

    virtual std::vector<double> computeLogParDer(std::vector<std::unique_ptr<class Particle>>& particles) {
        return std::vector<double>();
    }

protected:
    int m_numberOfParameters = 0;
    std::vector<double> m_parameters = std::vector<double>();

    WaveFunction(int numberOfParameters, std::vector<double> parameters)
        : m_numberOfParameters(numberOfParameters)
        , m_parameters(std::move(parameters)) {}
};

