#pragma once
#include <memory>
#include <vector>
#include <stdexcept>


class WaveFunction {
public:
    // Use the default deconstructor generated by the compiler
    virtual ~WaveFunction() = default;

    int getNumberOfParameters() { return m_numberOfParameters; }
    const std::vector<double>& getParameters() const { return m_parameters; }

    // Value of the trial wave function
    virtual double evaluate(std::vector<std::unique_ptr<class Particle>>& particles) = 0;

    // Sum of Laplacians acting on the wave function
    virtual double computeDoubleDerivative(std::vector<std::unique_ptr<class Particle>>& particles) = 0;

    // Logarithmic derivative with respect to alpha:
    // O_alpha(R) = d/dalpha ln Psi_alpha(R)
    // Needed for the VMC energy gradient estimator
    virtual double computeLogDerivativeAlpha(std::vector<std::unique_ptr<class Particle>>& particles) {
        throw std::logic_error("Single-parameter logarithmic derivative not implemented.");
    }

protected:
    int m_numberOfParameters = 0;
    std::vector<double> m_parameters = std::vector<double>();
};

