#pragma once
#include <memory>
#include <vector>

/**
 * @brief Abstract base class for the quantum system's Hamiltonian.
 * * Defines the interface for evaluating the local energy of the system.
 * Specific physics problems (e.g., interacting vs. non-interacting) will
 * inherit from this class and implement their own energy calculations.
 */
class Hamiltonian {
public:
    // Use the default deconstructor generated by the compiler
    virtual ~Hamiltonian() = default;

    /**
     * @brief Computes the local energy of the current particle configuration.
     * * The local energy is defined as E_L = (1 / Psi) * H * Psi, where H is the
     * Hamiltonian operator and Psi is the trial wave function.
     * * @param waveFunction Reference to the system's trial wave function.
     * @param particles Vector of unique pointers to the system's particles.
     * @param cache Reference to the WaveFunctionCache for optimized evaluations.
     * @return The local energy in natural units.
     */
    virtual double computeLocalEnergy(
        class WaveFunction& waveFunction,
        std::vector<std::unique_ptr<class Particle>>& particles,
        class WaveFunctionCache& cache
    ) {
        return -123;
    }

    virtual double computeLocalEnergy(
        class WaveFunction& waveFunction,
        std::vector<std::unique_ptr<class Particle>>& particles
    ) {
        return -123;
    }

    /**
     * @brief Toggles the use of analytical derivatives for kinetic energy.
     * @param val True to use analytical derivatives (if available), False to force numerical.
     */
    void set_analytic_ifAvailable(bool val);

    /**
     * @brief Retrieves the repulsive interaction parameter (hard-core diameter).
     * @return The value of 'a'. Returns 0.0 by default for non-interacting systems.
     */
    virtual double getRepulsiveFactor() const { return 0.0; }

    virtual double get_hardcore_strength() const { return 0.0; }

    virtual void set_hardcore_strength(double strength) {}
protected:
    bool m_analytic_ifAvailable = true;
};

