#pragma once
#include <memory>
#include <vector>

/**
 * @brief Abstract base class for the quantum system's Hamiltonian.
 * * Defines the interface for evaluating the local energy of the system.
 * Specific physics problems (e.g., interacting vs. non-interacting) will
 * inherit from this class and implement their own energy calculations.
 */
class Hamiltonian {
public:
    // Use the default deconstructor generated by the compiler
    virtual ~Hamiltonian() = default;

    virtual double computeLocalEnergy(
        class WaveFunction&,
        std::vector<std::unique_ptr<class Particle>>&,
        class WaveFunctionCache&
    ) {
        throw std::invalid_argument("computeLocalEnergy called on base class hamiltonian");
        return -1;
    }

    virtual double computeLocalEnergy(
        class WaveFunction&,
        std::vector<std::unique_ptr<class Particle>>&
    ) {
        throw std::invalid_argument("computeLocalEnergy called on base class hamiltonian");
        return -1;
    }

    /**
     * @brief Toggles the use of analytical derivatives for kinetic energy.
     * @param val True to use analytical derivatives (if available), False to force numerical.
     */
    void set_analytic_ifAvailable(bool val);

    virtual double getRepulsiveFactor() {
        throw std::invalid_argument("getRepulsiveFactor called on base class hamiltonian");
        return -1;
    }

    virtual double has_hardcore() {
        return false;
    }

    virtual double get_interaction_strength() {
        throw std::invalid_argument("get_hardcore_strength called on base class hamiltonian");
        return -1;
    }

    virtual void set_interaction_strength(double) {
        throw std::invalid_argument("set_hardcore_strenght called on base class hamiltonian");
    }

    virtual void set_percStrength(double) {
        throw std::invalid_argument("set_percStrength called on base class hamiltonian");
    }
protected:
    bool m_analytic_ifAvailable = true;
};

